### ISSUE TITLE
How to add to an existing Ember-CLI project?

### ISSUE THREAD

**Issue by chrisbenson** [mysterlune/ember-pdfjs#1]
I'd like to integrate this into an existing website, so that it displays a PDF on a specific route.  Thank you!

**Comment by mysterlune** [comment]
@chrisbenson Me too! ;)

This addon is very much in its infancy. In fact, there's pretty much nothing that it currently does beyond adding a configuration value to properly target the `pdf.worker.js` file.

The way that I've added PDFJS to an application is by pulling all of the files from https://github.com/mozilla/pdfjs-dist and doing the following with them:
- Using ember-cli for project scaffolding
- Add the PDFJS files manually to the `public` folder like:

`[project dir]/public/pdf.js/build` (contains pdf.js, compatibility.js, and pdf.worker.js)
`[proejct dir]/public/pdf.js/web` (contains ui_utils.js, text_layer_builder.css, text_layer_builder.js)
`[project dir]/public/pdf.js/cmaps` (contains all the cmaps included with the distribution)
- In your app's index.html, add the following in the `head` tag

```
<link rel="stylesheet" href="pdf.js/web/text_layer_builder.css">
```
- ... and this in your body tag under the other `script` tags:

```
<script src="pdf.js/build/pdf.js"></script>
<script src="pdf.js/build/compatibility.js"></script>
<script src="pdf.js/build/pdf.worker.js"></script>
<script src="pdf.js/web/ui_utils.js"></script>
<script src="pdf.js/web/text_layer_builder.js"></script>
```

PDFJS is (from an Ember dev's standpoint) a kinda difficult third-party include. There's a ton of code in there, and is not exactly set up to work with an ES6 transpiler.

For now, this manual step is the best I can offer. Once you have the `PDFJS` object in your project, you can pretty easily follow along with this great tutorial I started out with on Medium [here](https://medium.com/@gordon_cassie/using-pdf-js-in-an-ember-view-ec2626a3ac66).

About your "specific route" question, I'd need to know a bit more about what you're trying to do. Also, the #ember IRC channel is a great place to get implementation help. You can hit me up there, or reply to this issue.

**Comment by mysterlune** [comment]
hey @chrisbenson, take a look at the updated README.md for instructions on how to integrate this with your project...

however, the `pdf-page` component only serves, well, one page currently ;) 

but either way, this addon will bring the `PDFJS` and `PDFJS.workerSrc` globals into your project!

**Comment by chrisbenson** [comment]
Thank you for letting me know!
