### ISSUE TITLE
TypeError: pdfjsLib is undefined

### ISSUE THREAD

**Issue by manukbenjamin** [mysterlune/ember-pdfjs#12]
Ember version : 2.5.1

I have installed ember-pdfjs in my project. After installing I was not able to start project, as it says     

> "broccoli-merge-trees",  "broccoli-static-compiler" is missing.

 I installed both and after starting my route was not loading. In console I got the error 

> 'TypeError: pdfjsLib is undefined'

Please provide a solution for the same. Anyone else got this error?

**Update**

Issue is in 

> bower_components/pdfjs-dist/web/pdf_viewer.js

**Comment by mgilroy** [comment]
I have had the same issue in ember 2.4.6. Made it slightly further making the following changes:

bower.json pick:

```
"pdfjs-dist": "1.4.20"
```

Update the environment.js contentSecurityPolicy to include:

```
  'child-src': "'self'",
  'img-src': "'self' blob: www.google-analytics.com",
```

I now get a pdf to display, however, only 4 pages show.

**Comment by DarrenDrumm** [comment]
Hi, Just wondering if you are keeping this project up-to-date? Does not appear to work correctly with ember 10.0.2.

**Comment by mysterlune** [comment]
yes. project up to date.

i just made some updates so the addon is of "proper" structure ;)... moved PDFJS to a service injection for the provided component.

there is still work to do here... so please contribute if you have needs or suggestions. happy to collaborate and make this addon excellent.
