### ISSUE TITLE
Error with pdfjs-dist >= 1.7.337

### ISSUE THREAD

**Issue by ntodd** [mysterlune/ember-pdfjs#17]
`Uncaught Error: Could not find module '../build/pdf.js' imported from '(require)'`

Looks like this is the commit that broke it: https://github.com/mozilla/pdfjs-dist/commit/a88a99517c5ddf8ba8ff6514429a9217e5a59a20#diff-81859d79710fc24b108a056f7a7313de

```
pdfjsLib = require('../build/pdf.js');
```

Workaround for now appears to be specifying `"pdfjs-dist": "1.7.331"` in `bower.json`.

**Comment by mysterlune** [comment]
hi @ntodd, thanks for the heads-up.

**Comment by mysterlune** [comment]
okay, i updated the `bower.json` file to pin the version you suggested. meanwhile, i'll investigate the changes to PDFJS that make the module export messy at the late version...

**Comment by ntodd** [comment]
Great, I'll try to help where possible.

**Comment by mysterlune** [comment]
hey @ntodd, i submitted an issue to the pdf.js group to inquire about whether the failing conditional is making correct assumptions... e.g. what really is the matter here :)

https://github.com/mozilla/pdf.js/issues/8146

please feel free to add any commentary on that ticket you think may be helpful.

**Comment by mysterlune** [comment]
also as a temporary measure, i had to update the blueprint's target version... which was ">=1.0.0"... so all the apps using this would be forced to latest version.

published 0.4.7

**Comment by mysterlune** [comment]
hey @ntodd, https://github.com/mozilla/pdf.js/pull/8154 is currently in review to sort out the error you were discovering.

**Comment by mysterlune** [comment]
the patch got merged (https://github.com/mozilla/pdf.js/pull/8154), and the issue ticket was resolved (https://github.com/mozilla/pdf.js/issues/8146).

closing this one for now, and will update the PDFJS dist dependency when it is bundled (i guess it's a nightly distribution?)... 

thanks for the support on this one!
